INSERT INTO greetings (language, greeting) VALUES('Setswana', 'Dumela'); 
INSERT INTO greetings (language, greeting) VALUES('SeSotho', 'Lekae'); 
INSERT INTO greetings (language, greeting) VALUES('isZulu', 'Sawubpna'); 
INSERT INTO greetings (language, greeting) VALUES('Sepedi', 'Thobela'); 
INSERT INTO greetings (language, greeting) VALUES('English', 'Hello'); 
INSERT INTO greetings (language, greeting) VALUES('Arabic', 'Morhaba'); 
INSERT INTO greetings (language, greeting) VALUES('Japanese', 'Konnichwa'); 
INSERT INTO greetings (language, greeting) VALUES('Swati', 'Sawubon'); 
INSERT INTO greetings (language, greeting) VALUES('Xitsonga', 'Avuxeni'); 
